# Generated by Django 5.2.17 on 2026-08-23 05:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
