# Generated by Django 5.2.17 on 2026-08-24 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_create_at_event_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="explanation",
            new_name="description",
        ),
    ]
