# Generated by Django 5.2.17 on 2026-08-24 09:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_rename_explanation_event_description"),
        ("interactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Review",
            new_name="Rating",
        ),
    ]
