# Generated by Django 5.2.17 on 2026-08-25 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_explanation_event_description'),
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='source',
            field=models.CharField(choices=[('manual', '検索画面'), ('preference', '通知設定')], default='manual', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'preference')), fields=('owner',), name='unique_preference_search_per_user'),
        ),
    ]
